name: ci

on:
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore VnDocSign.sln

      - name: Build
        run: dotnet build VnDocSign.sln -c Release --no-restore

      - name: Test
        run: dotnet test VnDocSign.sln -c Release --no-build --verbosity normal
